# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "FlowerRr"
license = "MIT"
licenselink = "https://github.com/qvshuo/hugo-theme-FlowerRr/blob/master/LICENSE"
description = "A simple hugo theme."
homepage = "https://github.com/qvshuo/hugo-theme-FlowerRr"
tags = []
features = []
min_version = "0.41"

[author]
  name = "yhz"
  homepage = "https://qvshuo.faith/"